# Generated by Django 3.2.4 on 2021-06-09 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_no', models.CharField(max_length=12, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrimaryAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=100, verbose_name='Address line 2')),
                ('pin_code', models.CharField(max_length=12, verbose_name='Postal code')),
                ('village', models.CharField(max_length=50, verbose_name='Village')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100, verbose_name='Address line 1')),
                ('address2', models.CharField(max_length=100, verbose_name='Address line 2')),
                ('pin_code', models.CharField(max_length=12, verbose_name='Postal code')),
                ('village', models.CharField(max_length=50, verbose_name='Village')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('country', models.CharField(max_length=100)),
                ('farmer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveryapp.farmer')),
            ],
        ),
        migrations.AddField(
            model_name='farmer',
            name='primary_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deliveryapp.primaryaddress'),
        ),
    ]
